# Generated by Django 4.0.1 on 2023-04-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('bgimg', models.ImageField(upload_to='')),
                ('hkimg', models.ImageField(upload_to='')),
                ('type', models.CharField(choices=[('1', 'Image'), ('2', 'File'), ('3', 'Link')], max_length=100)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('reward', models.IntegerField()),
            ],
        ),
    ]
