# Generated by Django 4.0.1 on 2023-04-15 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HackathonApp', '0003_alter_hackathonmodel_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonmodel',
            name='bgimg',
            field=models.ImageField(upload_to='images/bgimages'),
        ),
        migrations.AlterField(
            model_name='hackathonmodel',
            name='hkimg',
            field=models.ImageField(upload_to='images/hkimages'),
        ),
        migrations.AlterField(
            model_name='hackathonmodel',
            name='type',
            field=models.CharField(choices=[('Image', 'Image'), ('File', 'File'), ('Link', 'Link')], max_length=100),
        ),
        migrations.CreateModel(
            name='SubmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('summary', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('coverimg', models.ImageField(upload_to='images/coverimages')),
                ('subimg', models.ImageField(blank=True, null=True, upload_to='images/subimages')),
                ('sublink', models.URLField(blank=True, null=True)),
                ('subfile', models.FileField(blank=True, null=True, upload_to='images/subfile')),
                ('hackathonid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HackathonApp.hackathonmodel')),
            ],
        ),
    ]
