# Generated by Django 4.0.1 on 2023-04-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackathonApp', '0004_alter_hackathonmodel_bgimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmodel',
            name='subfile',
            field=models.FileField(blank=True, default='-', null=True, upload_to='images/subfile'),
        ),
        migrations.AlterField(
            model_name='submissionmodel',
            name='sublink',
            field=models.URLField(blank=True, default='-', null=True),
        ),
    ]
