# Generated by Django 4.0.1 on 2023-04-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackathonApp', '0005_alter_submissionmodel_subfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmodel',
            name='sublink',
            field=models.URLField(blank=True, default='https://null.com', null=True),
        ),
    ]
