# Generated by Django 4.0.1 on 2023-04-16 05:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HackathonApp', '0008_submissionmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmodel',
            name='subfile',
            field=models.FileField(blank=True, default='-', null=True, upload_to='images/subfile', validators=[django.core.validators.FileExtensionValidator(['pdf', 'csv', 'docx', ''])]),
        ),
        migrations.AlterField(
            model_name='submissionmodel',
            name='subimg',
            field=models.ImageField(blank=True, null=True, upload_to='images/subimages', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg', 'ico', ''])]),
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userfavorites', models.ManyToManyField(blank=True, related_name='userfavorites', to='HackathonApp.SubmissionModel')),
                ('usersubmissions', models.ManyToManyField(blank=True, related_name='usersubmissions', to='HackathonApp.SubmissionModel')),
            ],
        ),
    ]
