# Generated by Django 4.0.1 on 2023-04-16 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HackathonApp', '0009_alter_submissionmodel_subfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='usersubmissions',
        ),
        migrations.AddField(
            model_name='submissionmodel',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
