# Generated by Django 4.0.1 on 2023-04-16 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HackathonApp', '0010_remove_usermodel_usersubmissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmodel',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
