# Generated by Django 4.0.1 on 2023-04-16 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HackathonApp', '0013_remove_submissionmodel_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionmodel',
            name='userid',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
