# Generated by Django 4.0.1 on 2023-04-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackathonApp', '0022_remove_submissionmodel_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionmodel',
            name='userid',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
