# Generated by Django 4.0.1 on 2023-04-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackathonApp', '0023_submissionmodel_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmodel',
            name='userid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
