# Generated by Django 4.0.1 on 2023-04-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HackathonApp', '0024_alter_submissionmodel_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionmodel',
            old_name='userid',
            new_name='username',
        ),
    ]
